# Generated by Django 2.2.3 on 2019-07-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿記事', 'verbose_name_plural': '投稿記事'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='記事内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/%Y/%m/%d', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.TextField(choices=[(1, 'airplane'), (2, 'automobile'), (3, 'bird'), (4, 'cat'), (5, 'deer'), (6, 'dog'), (7, 'frog'), (8, 'horse'), (9, 'ship'), (10, 'truck')], null=True, verbose_name='ラベル'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
