# Generated by Django 2.2.3 on 2019-07-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190727_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.TextField(blank=True, choices=[(1, 'airplane'), (2, 'automobile'), (3, 'bird'), (4, 'cat'), (5, 'deer'), (6, 'dog'), (7, 'frog'), (8, 'horse'), (9, 'ship'), (10, 'truck')], null=True, verbose_name='ラベル'),
        ),
    ]
